// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlwoiakcrojpvvpuyoqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsd29pYWtjcm9qcHZ2cHV5b3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjgwMTMsImV4cCI6MjA1ODA0NDAxM30.1tv5n0BcYfpPk0kWhqWA0xK3UFsQyYhOU3cHvAYHmx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);